version: '2'
services:
  mezzanine:
    image: mezzanine3
    restart: unless-stopped
    cap_drop:
      - ALL
    volumes:
      - ./mezzanine:/srv/mezzanine
      - mezzanine_nginx_config:/etc/nginx/conf.d

    environment:
      MEZZANINE_PROJECT: khorlo

  nginx:
    image: nginx:stable
    restart: unless-stopped
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETUID
      - SETGID
    #volumes_from:
    #  - mezzanine:ro
    depends_on:
      - mezzanine
    volumes:
      - ./mezzanine:/srv/mezzanine
      - mezzanine_nginx_config:/etc/nginx/conf.d
    ports:
      - 80:8080/tcp
      # - 443:443/tcp

volumes:
  mezzanine_nginx_config: {}
  mezzanine_projects: {}

